+info program
Program stopped.
It stopped after stepping, next'ing or initial start.
+continue
*** Uncaught exception. Entering post mortem debugging
*** Running 'c' or 'step' will restart the program
+info program
The program being debugged is not being run.
+######################################
+### Program munges sys.argv
+### see if we can rerun it okay
+######################################
+set interactive on
+run 3 5
Restarting gcd.py with arguments:
	3 5
+######################################
+### Break of a fn name and
+### Try a return where there is none
+### either because not in subroutine
+### or no "return" statement
+######################################
+set interactive off
+break check_args
Breakpoint 1 set in file gcd.py, line 13.
+return
*** I don't see that we are in a subroutine.
+continue
+return
Sorry; a return statement was not found.
+######################################
+### rerun wrong number of parameters
+### that causes and exception
+### and use "info program" to check
+### termination
+######################################
+set interactive on
+info program
Program stopped.
It stopped at breakpoint 1.
+run 5 10
Restarting gcd.py with arguments:
	5 10
+continue
+break gcd
Breakpoint 2 set in file gcd.py, line 24.
+continue
+info program
Program stopped.
It stopped at breakpoint 2.
+set linetrace on
+set interactive off
+return
(gcd.py:32):  gcd
+where
-> 0 gcd(a=5, b=10) called from file 'gcd.py' at line 32
## 1 in file 'gcd.py' at line 41
## 2 in exec cmd in globals, locals at line 1
## 3 run(self=<__main__.Pdb instance a...) called from file 'bdb.py' at line 366
+quit
